sudo: required #we need super level permissions to execute build
services: #tells travis to install docker
  - docker
before_install:
  - docker build -t ccincotti3/docker-react -f Dockerfile.dev . #get image ID, reference it by tag

script: #Commands to be executed, if something fails, travis reports the build failed
  - docker run ccincotti3/docker-react npm run test -- --coverage #coverage because it exits. Default run test behavior is to prompt user 

