language: node_js
sudo: required #we need super level permissions to execute build
services: #tells travis to install docker
  - docker
before_install:
  - docker build -t ccincotti3/docker-react -f Dockerfile.dev . #get image ID, reference it by tag

script: #Commands to be executed, if something fails, travis reports the build failed
  - docker run ccincotti3/docker-react npm run test -- --coverage #coverage because it exits. Default run test behavior is to prompt user 

deploy: 
  provider: elasticbeanstalk #travis CI comes preconfigured to handle a bunch of providers
  region: "us-east-2" #find in AWS DockerReact-env's URL: DockerReact-env.juqihfxrpq.us-east-2.elasticbeanstalk.com
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-563420165989" # Services > Search for "S3"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"